### PR TITLE
Avol parse bb

### PR DESCRIPTION
**Pull request by sallamander**
@dansbecker First pass at parsing the `alov` bounding boxes (misnamed branch, woops). Right now all it does is take in folder name and simply create a `.csv` that contains 2 columns that will help navigate to the folders, and then others denoting what frames (image numbers) to grab and where the bounding boxes are located. 

I still need to add column names at the top (easy), and then adjust the Makefile at some point to actually move/grab the frames that we want and put them somewhere in our file structure. But, I think the majority of this is done. 

It's arguable whether this took me longer with bash than it would have python, depending on the number of things I had to look up.

### CODE REVIEW

**Comment by dansbecker** [comment]
I don't know if it took longer to write in bash or python, but my hunch is that the Python version would be easier to read (and maintain).  I have to say, I'm really impressed how quickly you got this together.

**Comment by sallamander** [comment]
Now that I know exactly what to do, I could put together a Python script tomorrow for this. It wouldn't take long. Thoughts? Doesn't matter to me either way. 

Also, where do we want to store the frame images that we will actually use? I could see either storing them in an `images` folder in the `alov` (e.g. we're pulling the ones we need from the `frames` folder), or just deleting the ones we don't want from the `frames` folder all together. Thoughts?

**Comment by dansbecker** [comment]
I think a Python script will be easier to maintain and extend. So my preference would be to eat the small time cost up front, rather than a little at a time whenever we want to change the bash script.

I'd keep the videos where they are, and put the frames in work/alov_frames, since we are moving outside the realm of raw data.  Now that I think about it, the bbox csv's should go somewhere in work too.

**Comment by sallamander** [comment]
Okay, right on. I'll put that together tomorrow. I can replace the other XML parser with a python script, too. Is that something we want to do as well? 

Okay, that sounds good. The bbox csv's are already set to go in work (the makefile has them going in work/ILSVRC/).

**Comment by dansbecker** [comment]
I probably would... I expect us to do less experimentation with the xml
than with video frames... so, it seems less important to put in python, but
probably still worthwhile.

**Comment by sallamander** [comment]
Cool, cool. I'll take care of this today.

**Comment by sallamander** [comment]
Merging this (after merging your `Makefile` changes into this), and opening a new branch to port everything to Python. Rather than leave this branch open, which was to get this done in bash, I think it might be better to close and open another? 

Let me know if this was a bad idea, and I'll avoid it in the future.

**Comment by dansbecker** [comment]
Close it and open a new PR sounds great.  In general, short-lived branches
are easier to code review, minimize merge conflicts, and make development
more fun.

**Pull request merged**
